### ISSUE TITLE
Option to only include JS/CSS when shortcode is used?

### ISSUE THREAD

**Issue by dominic-p** [smashballoon/instagram-feed#25]
First, I wanted to say thanks for the great plugin.

As I was browsing the code, it looks like the CSS is loaded on every page and the JS is loaded on every page unless the `sb_instagram_ajax_theme` setting is enabled. However, it looks like if that setting is enabled, the shortcode outputs a script tag directly to the page instead of using the WP preferred method of `wp_enqueue_script()`.

What would you think about giving users the option to only enqueue the CSS and JS when the shortcode is used? Then, if the option is enabled, the code that outputs the shortcode could simply call `wp_enqueue_script()` and `wp_enqueue_style()` to include the needed resources.

I would be excited to use the plugin, but I don't want to add 8k of minified CSS and 22k of minifed JS to 100% of my pages when they will only be needed on <1%.

I would be happy to put together a pull request if you would like.

**Comment by craigschlegel** [comment]
Hey Dominic-p,

This is definitely a good point. We've already changed this in the "Pro" version and are contemplating adding it to the "Free" version. It turns out that enqueing in the shortcode only does not work on about 1% of sites from what we can tell so far. This might be due to the specific themes but we are looking into how best to add this to the free version but not cause a lot of problems on sites if that makes sense. It will likely end up like you described as an option that can be enabled.

It's not hard to modify the existing plugin to work the way you're hoping luckily. I'll see if I can create a branch for you to download and use if that would be easiest. It might take a few days due to some other projects we are wrapping up this week.

**Comment by dominic-p** [comment]
Thanks @craigschlegel for the quick and informative reply. Yeah, I would guess some poorly coded themes might create problems for enqueuing in shortcodes which should be supported.

I will keep an eye out for any upcoming updates or branches.

**Comment by craigschlegel** [comment]
Hey again dominic-p,

It looks like your tweak for including the admin files only in the admin area will be released in the next update on wordpress.org. Thanks again for that!

We are also going to include an option for the CSS/JS files to be added using the shortcode rather than on every page. You can check out release 1.6 for this code already in use (no option to disable or enable it yet) [https://github.com/smashballoon/instagram-feed/tree/release/1.6](https://github.com/smashballoon/instagram-feed/tree/release/1.6)

**Comment by dominic-p** [comment]
You're welcome, and thanks for making those other changes! The 1.6 release code looks great to me, and I look forward to using it.
